-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 22, 2022 at 07:57 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `projet_telecom`
--

-- --------------------------------------------------------

--
-- Table structure for table `course`
--

CREATE TABLE `course` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nb_enrollments` int(11) DEFAULT NULL,
  `details` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `link` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nb_likes` int(11) NOT NULL,
  `rate` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`id`, `name`, `image`, `nb_enrollments`, `details`, `link`, `nb_likes`, `rate`) VALUES
(1, 'IBM Cybersecurity Analyst', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/67/6a8a23c93d424fa3a39138428681f3/Professional_Certificate_-_IBM_Cybersecurity_Analyst.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Agile Software Development, Application Development, Cloud Computing, Cloud Infrastructure, Cloud Management, Computer Architecture, Computer Networking, Computer Programming, Computer Security Incident Management, Computer Security Models, Cryptography, Cyberattacks, Data Analysis, Data Management, Data Structures, Data Warehousing, Database Administration, Database Application, Databases, DevOps, Distributed Computing Architecture, Encryption, Entrepreneurship, Finance, Information Security, Leadership and Management, Linux, Marketing, Mathematics, Mobile Development, Mobile Security, Network Analysis, Network Architecture, Network Model, Network Security, Networking Hardware, Operating Systems, Python Programming, Regulations and Compliance, SQL, Sales, Security Engineering, Security Software, Security Strategy, Software Engineering, Software Security, Software Testing, Statistical Programming, Strategy, Strategy and Operations, System Security, Theoretical Computer Science, Virtual Machine', 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst', 0, 4.6),
(2, 'Introduction to Cyber Security', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/e5/5b94f0bb5811e78eb4ffb2bb669fdb/Introduction-to-Cyber-Security.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Algorithms, BlockChain, Computer Networking, Computer Security Models, Cryptography, Cyberattacks, Finance, Leadership and Management, Mobile Development, Mobile Security, Network Security, Operating Systems, Risk, Risk Management, Security, Security Engineering, Security Software, Software Security, System Security, Theoretical Computer Science', 'https://www.coursera.org/specializations/intro-cyber-security', 0, 4.7),
(3, 'Cybersecurity for Everyone', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/b5/c8eb7fee7f409dbd31ececb1d1a82e/MOOCs_Cybersecurity.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Free', 'https://www.coursera.org/learn/cybersecurity-for-everyone', 0, 4.7),
(4, 'IT Fundamentals for Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/92/13ececb5a44bb7a15d6fb8d4d1433e/IT_Fund_for_Cyber_Specialist.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Application Development, Cloud Computing, Cloud Infrastructure, Cloud Management, Computer Architecture, Computer Networking, Computer Security Incident Management, Cryptography, Cyberattacks, Data Management, Data Structures, Data Warehousing, Database Administration, Database Application, Databases, Distributed Computing Architecture, Finance, Leadership and Management, Linux, Network Architecture, Network Security, Networking Hardware, Operating Systems, Process, Regulations and Compliance, SQL, Security, Security Engineering, Security Strategy, Software Engineering, Software Security, Software Testing, Statistical Programming, System Security, Theoretical Computer Science', 'https://www.coursera.org/specializations/it-fundamentals-cybersecurity', 0, 4.6),
(5, 'Google IT Support', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/14/b2d530f1ad11e7ab380fc0c6c817a8/Search-Thumbnail.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Cloud Computing, Cloud Platforms, Cloud Storage, Communication, Computer Architecture, Computer Graphics, Computer Networking, Cryptography, Cyberattacks, Data Architecture, Data Management, Database Administration, Database Application, Databases, Entrepreneurship, Hardware Design, Human Computer Interaction, Interfaces, Leadership and Management, Marketing, Mathematics, Microarchitecture, Network Architecture, Network Security, Networking Hardware, Operating Systems, Planning, Powershell, Process, Product Lifecycle, Sales, Security, Security Engineering, Security Software, Security Strategy, Software As A Service, Software Security, Strategy, Strategy and Operations, Supply Chain and Logistics, System Security, Systems Design, Theoretical Computer Science, Virtual Reality, Writing', 'https://www.coursera.org/professional-certificates/google-it-support', 0, 4.8),
(6, 'Python for Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/db/69857216fa4adc91484d95d473cae9/Coursera_Python_for_CS_600x600.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Computer Networking, Computer Programming, Computer Programming Tools, Computer Security Incident Management, Cryptography, Cyberattacks, Encryption, Mathematics, Network Analysis, Network Security, Operating Systems, Python Programming, Security, Security Engineering, Software Security, Statistical Programming, System Security', 'https://www.coursera.org/specializations/pythonforcybersecurity', 0, 4.4),
(7, 'Palo Alto Networks Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/5d/b56c5478a7475489876a54b99f9586/AcademyLogo2020.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Cloud Computing, Cloud Infrastructure, Cloud Platforms, Computer Architecture, Computer Networking, Cyberattacks, Epidemiology, Finance, Leadership, Marketing, Network Architecture, Network Model, Network Security, Operating Systems, Probability & Statistics, Risk Management, Sales, Security, Security Engineering, Security Software, Security Strategy, Software As A Service, Software Security, Strategy, Strategy and Operations, System Security', 'https://www.coursera.org/professional-certificates/palo-alto-networks-cybersecurity-fundamentals', 0, 4.6),
(8, 'Introduction to Cybersecurity Tools & Cyber Attacks', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/a1/4d3f79658647c595a756fba0e715e8/hacker.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Computer Security Incident Management, Security Engineering, Operating Systems, Network Security, Theoretical Computer Science, Leadership and Management, Computer Networking, Security, Cyberattacks, System Security', 'https://www.coursera.org/learn/introduction-cybersecurity-cyber-attacks', 0, 4.5),
(9, 'Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/9e/914690c15511e5b8ef55bf49294387/logo_small.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Authentication, Business Psychology, Computer Architecture, Cryptography, Design and Product, Encryption, Hardware Design, Human Computer Interaction, Mathematical Theory & Analysis, Mathematics, Numbers (Spreadsheet), Operating Systems, Password, Privacy, Research and Design, Security Engineering, Software, Software Engineering, Software Security, System Security, Systems Design, Theoretical Computer Science, User Experience, User Experience Design', 'https://www.coursera.org/specializations/cyber-security', 0, 4.6),
(10, 'Introduction to Cybersecurity Foundations', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/65/fd51188f0947bca11e033130a0a9b9/Coursera_Cybersecurity_Foundations_1200x1200.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Free', 'https://www.coursera.org/learn/introduction-to-cybersecurity-foundations', 0, NULL),
(11, 'Cybersecurity for Tech Professionals', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/14/89f12ec2db4a439891b86b9e003540/Imagen_Portada-1200x1200.jpg?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Free', 'https://www.coursera.org/learn/cybersecurity-for-tech-professionals', 0, 4.3),
(12, 'Introduction to Cybersecurity Essentials', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/df/46c3972a89409d8e61d5cc5cc3ad16/Intro-to-Cybersecurity-Essentials-Temp-no-watermark-.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h', NULL, 'Skills you\'ll gain: Software Security, Security Engineering, Operating Systems, Mobile Security, Security Software, Mobile Development, Information Security, Computer Networking, Network Security, System Security, Security, Cyberattacks', 'https://www.coursera.org/learn/introduction-to-cybersecurity-essentials', 0, 4.8),
(13, 'Cybersecurity MasterTrack® Certificate', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/ddp/branding/asu/cybersecurity-asu-thumbnail.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Architecture, Software Architecture, Communication, Databases, BlockChain, Security Engineering, Finance, Tableau Software, Machine Learning, Operating Systems, Statistical Programming, General Statistics, Probability & Statistics, Artificial Neural Networks, Computer Programming, Data Visualization, Data Analysis, SQL, Feature Engineering, Software, Theoretical Computer Science, Bayesian Network, Mobile Development, Software Testing, Geovisualization, Computer Networking, Programming Principles, Deep Learning, System Security, Hardware Design, Algorithms, Entrepreneurship, Software Engineering, Network Security, Data Mining, Journalism', 'https://www.coursera.org/mastertrack/cybersecurity-asu', 0, NULL),
(14, 'Master of Science in Cyber Security', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/ddp/branding/msc-cyber-security-london/msc-cyber-security-london-thumbnail.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Earn a degree', 'https://www.coursera.org/degrees/msc-cyber-security-london', 0, NULL),
(15, 'Security Analyst Fundamentals', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/ff/bb72be199142e099170a3cbc2e129a/Security_Analyst_Fundamentals_Specialization.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Agile Software Development, Case Study, Computer Networking, Computer Programming, Computer Security Incident Management, Cyberattacks, Data Analysis, Database Administration, Databases, DevOps, Entrepreneurship, Leadership and Management, Marketing, Mathematics, Mobile Development, Mobile Security, Network Analysis, Network Security, Operating Systems, Python Programming, Sales, Security, Security Engineering, Security Software, Security Strategy, Software Engineering, Software Security, Software Testing, Statistical Programming, Strategy, Strategy and Operations, System Security', 'https://www.coursera.org/specializations/security-analyst-fundamentals', 0, 4.6),
(16, 'Introduction to Cybersecurity & Risk Management', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/22/10f622e5fa47578966a924ebb35047/info-security-overall-coursera600x600.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Advertising, Communication, Computer Networking, Employment, Entrepreneurship, Finance, Human Resources, Leadership and Management, Marketing, Network Architecture, Networking Hardware, Operations Management, Probability & Statistics, Risk, Risk Management, Sales, Security, Security Engineering, Security Strategy, Statistical Tests, Strategy, Strategy and Operations', 'https://www.coursera.org/specializations/information-security', 0, 4.6),
(17, 'IT Security: Defense against the digital dark arts', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/af/d5ed10f26911e7a930e510b0715979/Course-Logo-6---NEW.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Cryptography, Theoretical Computer Science, Security Engineering, Network Security, Computer Networking, System Security, Software Security, Wireless, Security Strategy, Security Software, Strategy and Operations, Operating Systems, Entrepreneurship, Encryption, Sales, Leadership and Management, Marketing, Security, Strategy, Cyberattacks', 'https://www.coursera.org/learn/it-security', 0, 4.8),
(18, 'Introduction to Cyber Attacks', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/2e/fab2a0bb5711e797d69d8eb3c0ee4d/Introduction-to-Cyber-Attacks.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Risk Management, Cryptography, Security Engineering, Finance, Leadership and Management, Threat, Risk, Security, Cyberattacks', 'https://www.coursera.org/learn/intro-cyber-attacks', 0, 4.7),
(19, 'Managing Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/c0/1a19e96a574fdc83336b9ff2780c1e/CyberEye-Square.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Accounting, Audit, Business Psychology, Cloud Computing, Cloud Infrastructure, Computer Networking, Computer Security Incident Management, Cryptography, Cyberattacks, DevOps, Entrepreneurship, Finance, Leadership and Management, Marketing, Network Architecture, Network Security, Operating Systems, Organizational Development, Performance Management, Planning, Probability & Statistics, Problem Solving, Regulations and Compliance, Research and Design, Risk Management, Sales, Security, Security Engineering, Security Strategy, Statistical Tests, Strategy, Strategy and Operations, Supply Chain and Logistics, System Security, Theoretical Computer Science', 'https://www.coursera.org/specializations/managing-cybersecurity', 0, 4.7),
(20, 'Cybersecurity Awareness and Innovation', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/72/413d2ba4494e2cb583e6b3e4a8b094/Logotipo_1.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Free', 'https://www.coursera.org/learn/cybersecurity', 0, 4.7),
(21, 'Cybersecurity for Business', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/0c/1305a07ad711e7bf202b86e9d12272/logo.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Cloud Computing, Cloud Infrastructure, Computational Thinking, Computer Architecture, Computer Networking, Computer Programming, Computer Security Incident Management, Cryptography, Cyberattacks, Finance, Hardware Design, Information Security, Leadership and Management, Network Security, Operating Systems, Risk, Risk Management, Security, Security Engineering, Security Software, Software As A Service, Software Engineering, Software Security, Software Testing, System Security, Theoretical Computer Science', 'https://www.coursera.org/specializations/cyber-security-business', 0, 4.7),
(22, 'Advanced Python Scripting for Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/89/ffd414df434a36b92965e6b671cea8/Coursera_Advanced_Python_Scripting_600x600.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Computer Programming, Operating Systems, Python Programming, Security Engineering, Security Software, Software Security, Statistical Programming, System Security', 'https://www.coursera.org/specializations/advanced-python-scripting-for-cybersecurity', 0, 4.3),
(23, 'Introduction to Applied Cryptography', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/80/7876c0934e11e780e1e1710a71e68a/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Algorithms, Applied Mathematics, Computational Logic, Computer Architecture, Cryptography, Hardware Design, Mathematical Theory & Analysis, Mathematics, Security Engineering, Theoretical Computer Science', 'https://www.coursera.org/specializations/introduction-applied-cryptography', 0, 4.6),
(24, 'Homeland Security and Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/1c/7f58d000e811e7a1264dbca50cedbc/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Account Management, Accounting, Communication, Computer Networking, Computer Security Models, Cyberattacks, Data Management, Entrepreneurship, Finance, Leadership and Management, Marketing, Network Security, Operating Systems, Risk Management, Sales, Security Engineering, Security Strategy, Software Engineering, Software Security, Strategy, Strategy and Operations, Supply Chain and Logistics, System Security, Transportation Operations Management', 'https://www.coursera.org/specializations/homeland-security-cybersecurity', 0, 4.7),
(25, 'Cybersecurity in Healthcare (Hospitals & Care Centres)', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d9/36b3e08d7649e198550292a44fbaaa/SecureHospitals.eu-Coursera-logo-EU-flag.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Free', 'https://www.coursera.org/learn/cybersecurity-in-healthcare', 0, 4.6),
(26, 'Cybersecurity Compliance Framework & System Administration', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/41/3b25f3874445ab9d6831dbd39d95a3/LowRes-Original-168621112.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Security Engineering, Application Development, Theoretical Computer Science, Operating Systems, Cryptography, Software Engineering, Software Testing, Finance, Digital Signature, Encryption, Cyberattacks, Regulations and Compliance, Security', 'https://www.coursera.org/learn/cybersecurity-compliance-framework-system-administration', 0, 4.7),
(27, 'Penetration Testing, Incident Response and Forensics', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/ac/5d7a95dab042afbb23445e1dcc7e4f/157400517.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Computer Security Incident Management, Network Security, Security Engineering, Python Programming, Computer Programming, Software Testing, Leadership and Management, Computer Networking, Security, Language, Statistical Programming, Software Engineering, Cyberattacks', 'https://www.coursera.org/learn/ibm-penetration-testing-incident-response-forensics', 0, 4.6),
(28, 'Cybersecurity Job Search and Interviews: Getting Started', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d3/80f706e8bc407bb07d1101e038a636/Jobs-Logo.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Sources, Interview, Analysis', 'https://www.coursera.org/learn/cybersecurity-jobs', 0, 4.9),
(29, 'Real-Time Cyber Threat Detection and Mitigation', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/bf/e1bac0bb5711e797d69d8eb3c0ee4d/Real-Time-Cyber-Threat-Detection-and-Mitigation.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Security Software, Network Security, Security Engineering, Operating Systems, Software Security, System Security, Threat, Computer Networking, Cyberattacks', 'https://www.coursera.org/learn/real-time-cyber-threat-detection', 0, 4.7),
(30, 'Check Point Jump Start: Network Security', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/fa/21b7e0ff334afba568d4a6d67bc45e/jumpstart_notext.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Free', 'https://www.coursera.org/learn/check-point-jump-start-network-security', 0, 4.5),
(31, 'Cybersecurity for Managers', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/7f/79a634a2ec4079b35f69c6da955263/Imagen_Portada-1200x1200_00.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Free', 'https://www.coursera.org/learn/cybersecurity-for-managers', 0, 4.7),
(32, 'Cybersecurity and Its Ten Domains', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/e9/957fe0702411e4a0b53d9470331d4e/ComputerLock-Logo_2.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Security Engineering, Cryptography, Theoretical Computer Science, Network Security, Operating Systems, Computer Networking, Information Security, System Security, Leadership and Management, Cyberattacks, Security', 'https://www.coursera.org/learn/cyber-security-domain', 0, 4.3),
(33, 'Cybersecurity in the Cloud', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/b1/393130ecc411e7a62f073eaec9fa1e/cloud-comp-logo.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Account Management, Accounting, Cloud Computing, Computer Architecture, Computer Graphics, Computer Networking, Computer Programming, Computer Security Models, Cryptography, Cyberattacks, Data Management, Data Security, Database Administration, Databases, DevOps, Distributed Computing Architecture, Finance, Human Computer Interaction, Marketing, Network Architecture, Network Model, Network Security, Networking Hardware, Operating Systems, SQL, Sales, Security, Security Engineering, Software Security, Statistical Programming, System Security, Systems Design, Theoretical Computer Science, Web Development', 'https://www.coursera.org/specializations/cybersecurity-cloud', 0, 4.3),
(34, 'Cybersecurity Risk Management Framework', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/53/cddfe3f43d4136a967e778a664bef6/Coursera_Cybersecurity_Risk_Management_Framework_600x600.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Computer Architecture, Computer Networking, Finance, Leadership and Management, Network Architecture, Operating Systems, Regulations and Compliance, Risk Management, Security Engineering, System Security', 'https://www.coursera.org/specializations/cybersecurity-risk-management-framework', 0, 4.2),
(35, 'Advanced System Security Design', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/d7/c2ae81854b4aea9cccad9137d7f6a0/uclionImage.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Amazon Web Services, Cloud Computing, Cloud Load Balancing, Computer Networking, Cyberattacks, Modeling, Network Security, Privacy, Security, Security Engineering, Security Strategy', 'https://www.coursera.org/specializations/advanced-system-security-design', 0, 4.5),
(36, 'Cybersecurity Leadership and Management', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/a6/6b5c5e6f95434b80cf2ec7d1e87335/clm_600x600.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Corporate Bond, Entrepreneurship, Finance, Leadership, Leadership and Management, Marketing, Risk Management, Sales, Security Engineering, Security Strategy, Strategy, Strategy and Operations', 'https://www.coursera.org/specializations/cybersecurity-leadership', 0, 4.3),
(37, 'Cybersecurity: Developing a Program for Your Business', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/5c/ec8430e47c11e5942d3b1e5cb53ada/Cyber-Security.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Behavioral Economics, Business Analysis, Business Psychology, Business Transformation, Communication, Computational Thinking, Computer Architecture, Computer Graphics, Computer Networking, Computer Programming, Computer Security Incident Management, Cyberattacks, Decision Making, Design and Product, Employee Relations, Entrepreneurship, Finance, Human Computer Interaction, Human Factors (Security), Human Resources, Interactive Design, Internet Of Things, Leadership and Management, Marketing, Mobile Development, Mobile Security, Network Architecture, Operating Systems, Product Management, Risk Management, Sales, Security, Security Engineering, Security Strategy, Software Engineering, Software Security, Strategy, Strategy and Operations, System Security, Theoretical Computer Science, Training', 'https://www.coursera.org/specializations/cybersecurity-developing-program-for-business', 0, 4.5),
(38, '(ISC)² Systems Security Certified Practitioner (SSCP)', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/57/981f90ba8a11e78e9c5112f5be0b07/sscp-logo-600x600.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Accounting, Algorithms, Business Psychology, Change Management, Cloud Computing, Computer Architecture, Computer Networking, Computer Programming, Computer Security Incident Management, Cryptography, Cyberattacks, Data Management, Entrepreneurship, Finance, Leadership and Management, Management Accounting, Marketing, Mobile Development, Mobile Security, Network Architecture, Network Model, Network Security, Operating Systems, Organizational Development, Probability & Statistics, Security Engineering, Software Engineering, Software Security, Software Testing, Statistical Tests, Strategy and Operations, System Security, Theoretical Computer Science', 'https://www.coursera.org/specializations/sscp-training', 0, 4.7),
(39, 'The Foundations of Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d2/90817e70e44613969cc5663929652b/LockGlobe-Square.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Network Security, Security Engineering, Operating Systems, Computer Networking, Strategy and Operations, Security Strategy, Entrepreneurship, Sales, System Security, Marketing, Leadership and Management, Strategy, Cyberattacks', 'https://www.coursera.org/learn/foundations-cybersecurity', 0, 4.7),
(40, 'Cybersecurity Capstone: Breach Response Case Studies', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/17/e5c203d1a04d3cbb7a04738662671e/808157856.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Databases, Database Administration, Software Security, Network Security, Operating Systems, Security Engineering, DevOps, System Security, Computer Security Incident Management, Leadership and Management, Computer Networking, Case Study, Security, Cyberattacks', 'https://www.coursera.org/learn/ibm-cybersecurity-breach-case-studies', 0, 4.8),
(41, 'Managing Network Security', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/b4/6196b7225a433ba78b9ba1f3fe697b/CyberManagement1.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Cloud Infrastructure, Network Architecture, Security Engineering, Network Security, Cloud Computing, Theoretical Computer Science, Cryptography, Operating Systems, Computer Networking, Cyberattacks, System Security, Security, Accounting', 'https://www.coursera.org/learn/managing-network-cybersecurity', 0, 4.8),
(42, 'Palo Alto Networks Cybersecurity Foundation', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/af/c95c716eca46cba335943b7351f2af/AcademyFoundationLogo.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Security Engineering, Operating Systems, Network Architecture, Network Security, Cloud Computing Security, Cloud Infrastructure, Security Strategy, Cloud Computing, Computer Networking, Software Security, Sales, Strategy and Operations, Computer Architecture, Security, Cyberattacks, System Security, Software As A Service, Authentication', 'https://www.coursera.org/learn/palo-alto-networks-cybersecurity-foundation-a', 0, 4.7),
(43, 'Introduction to Python for Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0b/f4e51af0f844cdab87611d50655dfd/Coursera_Python_for_CS_600x600.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Python Programming, Cryptography, Security Engineering, Statistical Programming, Computer Programming, Cyberattacks', 'https://www.coursera.org/learn/pythonforcybersecurity-introduction', 0, 4.4),
(44, 'Security Awareness Training', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/4e/e6e2f9f8c04875a5efacdaf3ce473b/Logo-800x800.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Network Security, Security Engineering, Security Strategy, Operating Systems, System Security, Computer Networking, Software Security, Human Computer Interaction, Information Security, Password, Human Factors (Security), Cyberattacks, Security', 'https://www.coursera.org/learn/security-awareness-training', 0, 4.7),
(45, 'IT Infrastructure and Emerging Trends', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/56/2365f0901a11e8972ccbab4be05758/graphicstock-smart-city-with-smart-services-and-icons-internet-of-things-networks-and-augmented-reality-con', NULL, 'Skills you\'ll gain: Finance, BlockChain', 'https://www.coursera.org/learn/it-infrastructure-and-emerging-trends', 0, 4.8),
(46, 'Classical Cryptosystems and Core Concepts', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/75/c5ee10878711e7956b777c6e592a43/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Mathematics, Hardware Design, Theoretical Computer Science, Cryptography, Security Engineering, Computer Architecture, Computational Logic, Mathematical Theory & Analysis, Algorithms', 'https://www.coursera.org/learn/classical-cryptosystems', 0, 4.6),
(47, 'Security Governance & Compliance', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d6/25bc56da1a4d45b9403ebb0633e3a1/cyber1.jpg?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Security Engineering, Network Architecture, Risk Management, Strategy and Operations, Entrepreneurship, Computer Networking, Leadership and Management, Security Strategy, Sales, Marketing, Strategy, Finance', 'https://www.coursera.org/learn/security-governance-compliance', 0, 4.6),
(48, 'NIST 800-171', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/96/607dd2d9c74575bf18f89eff8618f6/Coursera_Cybersecurity_Risk_Management_Framework_1200x1200.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w', NULL, 'Skills you\'ll gain: Network Architecture, Operating Systems, Security Engineering, Computer Networking, Computer Architecture, System Security, Finance, Regulations and Compliance', 'https://www.coursera.org/learn/nist-800-171', 0, 4.3),
(49, 'Cloud Security Basics', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0f/cf9a604d7b11e8b82a47c025c81db6/cloud-comp-logo.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Software Security, Theoretical Computer Science, Operating Systems, Networking Hardware, Network Architecture, Security Engineering, Computer Networking, DevOps, Cloud Computing Security, Computer Security Models, Systems Design, Computer Architecture, Cryptography, Network Security, Network Model, Distributed Computing Architecture, Marketing, Accounting, Account Management, System Security, Sales, Security, Modeling', 'https://www.coursera.org/learn/cloud-security-basics', 0, 4.4),
(50, 'Cyber Threat Intelligence', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/10/ea358827b246ba84949876088a6053/692023983.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Network Security, Mobile Security, Strategy and Operations, Security Engineering, DevOps, Software Security, Security Software, Network Analysis, Computer Networking, Mobile Development, Entrepreneurship, Security Strategy, Leadership and Management, Operating Systems, Agile Software Development, Mathematics, Sales, Threat, System Security, Software Engineering, Cyberattacks, Strategy, Marketing, Security, Data Analysis', 'https://www.coursera.org/learn/ibm-cyber-threat-intelligence', 0, 4.7),
(51, 'Cybersecurity Roles, Processes & Operating System Security', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/4b/834f1caad14fa698f4be488b3fa65d/504473474.504473476.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Networking Hardware, Theoretical Computer Science, Software Security, Cloud Computing Security, Cloud Infrastructure, Security Engineering, Security Strategy, Computer Architecture, Computer Networking, Cloud Computing, Operating Systems, Cryptography, Process, Data Management, Distributed Computing Architecture, System Security, Security, Data Warehousing, Virtual Machine, Linux, Cloud Management, Leadership and Management', 'https://www.coursera.org/learn/cybersecurity-roles-processes-operating-system-security', 0, 4.6),
(52, 'Cybersecurity Risk Management Frameworks', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/2b/1cbf2e36e24413be00d303b33e9668/CyberSec-copy.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Adaptability, Business Communication, Business Psychology, Communication, Cyberattacks, Entrepreneurship, Finance, Human Resources, Human Resources Operations, Leadership and Management, Operating Systems, Probability & Statistics, Project, Project Management, Recruitment, Regulations and Compliance, Risk, Risk Management, Sales, Security Engineering, Software Security, Strategy and Operations, System Security, Writing', 'https://www.coursera.org/specializations/cybersecurity-risk-management-frameworks', 0, 4.5),
(53, 'IBM Cybersecurity Analyst Assessment', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0d/37e7204ef248268db4f1196ef2ae4e/Inline-910931322.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Operating Systems, Security Engineering, Software Security, Theoretical Computer Science, Network Architecture, Network Security, Cryptography, Strategy and Operations, Computer Networking, Computer Architecture, Threat, Information Security, Security, Network Model, Computer Security Models', 'https://www.coursera.org/learn/ibm-cybersecurity-analyst-assessment', 0, 4.8),
(54, 'Cybersecurity Foundations for Risk Management', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d2/90817e70e44613969cc5663929652b/LockGlobe-Square.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Probability & Statistics, Human Resources, Project Management, Writing, Security Engineering, Human Resources Operations, Risk Management, Operating Systems, Entrepreneurship, Finance, Software Security, Information Security, Leadership, Project, Leadership and Management, Risk, Sales, Strategy and Operations, System Security, Business Psychology, Recruitment, Adaptability, Cyberattacks, Security, Business Communication, Communication, Employment', 'https://www.coursera.org/learn/cybersecurity-foundations-for-risk-management', 0, 4.6),
(55, 'Introduction to Cybersecurity for Business', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/91/cd60907ad811e7983d2d33f9731b94/1a.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Theoretical Computer Science, Operating Systems, Security Engineering, Risk Management, Software Engineering, Computer Networking, Information Security, Finance, Leadership and Management, Cryptography, Network Security, Risk, Security, System Security', 'https://www.coursera.org/learn/intro-cyber-security-business', 0, 4.7),
(56, 'The GRC Approach to Managing Cybersecurity', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/14/01f9a7c5fd4cc38e3f609706811c99/Course2-GRC.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Risk Management, System Security, Sales, Operating Systems, Business Psychology, Security Strategy, Strategy and Operations, Leadership and Management, Finance, Entrepreneurship, Strategy, Organizational Development, Performance Management, Marketing, Regulations and Compliance, Security Engineering', 'https://www.coursera.org/learn/grc-approach-to-managing-cybersecurity', 0, 4.8),
(57, 'Homeland Security & Cybersecurity Connection - It\'s Not About the Terrorists', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/46/e6569000e911e79133cb840ebc9d68/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Security Engineering, Risk Management, Strategy and Operations, System Security, Operating Systems, Finance, Entrepreneurship, Security Strategy, Leadership and Management, Strategy, Marketing, Cyberattacks, Sales', 'https://www.coursera.org/learn/homeland-security-cybersecurity-connection', 0, 4.7),
(58, 'Cybersecurity Policy for Water and Electricity Infrastructures', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/71/e9b0d000e911e79e7605a580100e86/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Leadership, Risk Management, Security Engineering, Risk, Finance, Entrepreneurship, Computer Security Models, Security Strategy, Marketing, Modeling, Communication, Career, Sales, Resource', 'https://www.coursera.org/learn/cybersecurity-policy-water-electricity', 0, 4.6),
(59, 'Cybersecurity for Data Science', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/5a/c48099a3ff412f97993d623ef4c7ff/Cyber-Logo-2-.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Security Engineering, Research and Design, Security Strategy, Entrepreneurship, Interview, Security', 'https://www.coursera.org/learn/cybersecurity-for-data-science', 0, 3.9),
(60, 'Managing Cybersecurity Incidents and Disasters', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/6d/307c2122864df1b486be38862e724a/Course4.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Computer Security Incident Management, Security Engineering, Entrepreneurship, Research and Design, DevOps, Leadership and Management, Problem Solving, Sales', 'https://www.coursera.org/learn/managing-cybersecurity-incidents-and-disasters', 0, 4.8),
(61, 'Cybersecurity and the Internet of Things', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/42/c427d0e47b11e58924673e58025fe8/internet.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Computer Graphics, Network Architecture, Computer Networking, Computer Architecture, Internet, Software Engineering, Security, Internet Of Things, Interactive Design, Human Computer Interaction', 'https://www.coursera.org/learn/iot-cyber-security', 0, 4.6),
(62, 'Cybersecurity Policy for Aviation and Internet Infrastructures', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/ec/bbcc8000e911e79133cb840ebc9d68/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Security Engineering, Operating Systems, Network Security, Finance, Security Strategy, Software Security, System Security, Computer Networking, Leadership and Management, Principle, Sales, Marketing, Supply Chain and Logistics, Cyberattacks, Software Engineering, Transportation Operations Management', 'https://www.coursera.org/learn/cybersecurity-policy-aviation-internet', 0, 4.7),
(63, 'Homeland Security and Cybersecurity Future', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/2b/38a7d000ea11e79e7605a580100e86/UCCS-logo-small2.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Security Strategy, Euler\'S Totient Function, Strategy and Operations, Risk, Finance, Analysis, Security, Cyberattacks, Accounting, Account Management, Data Management, Sales, Security Engineering', 'https://www.coursera.org/learn/homeland-security-cybersecurity-future', 0, 4.6),
(64, 'Cybersecurity and Mobility', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0d/59fde0e47b11e5adba1dd0436e277d/mobility.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Security Engineering, Business Analysis, Operating Systems, Mobile Security, Mobile Development, Security Strategy, Business Transformation, Internet Of Things, System Security, Security', 'https://www.coursera.org/learn/cybersecurity-mobility', 0, 4.5),
(65, 'Cybersecurity and the X-Factor', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/e9/84c110e47b11e5ad7fc7f529dd2b43/xfactor.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Risk Management, Software Security, Human Resources, Decision Making, Theoretical Computer Science, Security Engineering, Operating Systems, Behavioral Economics, Computational Thinking, Strategy and Operations, Communication, Leadership and Management, Entrepreneurship, Human Factors (Security), Product Management, Training, Computer Programming, Sales, Security Strategy, Business Psychology, Threat, Strategy, Cyberattacks, Finance, Marketing, System Security, Employee Relations, Human Computer Interaction, Design and Product, Computer Security Incident Management', 'https://www.coursera.org/learn/cybersecurity-and-x-factor', 0, 4.6),
(66, 'Cybersecurity Capstone Project', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d1/744420e9f311e4be6de3a9b6c82d77/cybersecurity_capstone2.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Software Engineering', 'https://www.coursera.org/learn/cyber-security-capstone', 0, 4.2),
(67, 'The Business of Cybersecurity Capstone', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/37/614f70e47c11e593b1b127fa4a32f6/cap.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Strategy and Operations', 'https://www.coursera.org/learn/business-of-cybersecurity-capstone', 0, 4.9),
(68, 'IBM Technical Support', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/7b/99d363d6ca4ccdbf1257439fe0157c/IBM-Tech-Support-PC.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fill', NULL, 'Skills you\'ll gain: Benefits, BlockChain, Cloud Applications, Cloud Computing, Cloud Infrastructure, Cloud Platforms, Cloud Storage, Communication, Computer Architecture, Computer Graphics, Computer Networking, Computer Program, Computer Programming, Customer Relationship Management, Customer Success, Customer Support, Cyberattacks, Data Management, Database Administration, Database Application, Databases, DevOps, Finance, Human Computer Interaction, IBM Cloud, Interactive Design, Journalism, Leadership and Management, Marketing, Microarchitecture, Mobile Development, Mobile Security, Network Architecture, Network Model, Network Security, Networking Hardware, Operating Systems, Programming Principles, Project Management, Sales, Security, Security Engineering, Security Software, Software, Software Architecture, Software As A Service, Software Engineering, Software Framework, Software Security, Strategy and Operations, Supply Chain and Logistics, System Programming, System Security, System Software, Technical Support, Theoretical Computer Science, User Experience', 'https://www.coursera.org/professional-certificates/ibm-technical-support', 0, 4.7),
(69, 'Information Technology (IT) and Cloud Fundamentals', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/94/54ee8a12c64631b31372a6809659f1/IT-and-Cloud-Fundamentals-Specialization-Temp-no-watermark-.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&q=25&fit=fil', NULL, 'Skills you\'ll gain: BlockChain, Cloud Applications, Cloud Computing, Cloud Infrastructure, Cloud Platforms, Cloud Storage, Communication, Computer Architecture, Computer Graphics, Computer Networking, Computer Program, Computer Programming, Cyberattacks, Data Management, Database Administration, Database Application, Databases, DevOps, Finance, Human Computer Interaction, IBM Cloud, Interactive Design, Journalism, Leadership and Management, Microarchitecture, Mobile Development, Mobile Security, Network Architecture, Network Model, Network Security, Networking Hardware, Operating Systems, Programming Principles, Security, Security Engineering, Security Software, Software, Software Architecture, Software As A Service, Software Engineering, Software Framework, Software Security, System Programming, System Security, System Software, Theoretical Computer Science, User Experience', 'https://www.coursera.org/specializations/it-cloud-fundamentals', 0, 4.7),
(70, 'Network Security & Database Vulnerabilities', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/d4/2983c967af475885fdedc6712b5a4b/658188828.jpg?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Databases, Software Security, Statistical Programming, Database Administration, Database Application, Network Architecture, Theoretical Computer Science, Network Security, SQL, Computer Architecture, Computer Networking, Data Structures, Security, Data Management, Security Engineering', 'https://www.coursera.org/learn/network-security-database-vulnerabilities', 0, 4.7),
(71, 'Execution, persistence, privilege escalation and evasion', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/c4/600586f095429fa3b0dcbdd4a72772/Coursera_Python_for_CS_1200x1200.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Python Programming, Computer Programming, Statistical Programming, Operating Systems, Information Security, Cyberattacks, System Security, Security, Security Engineering', 'https://www.coursera.org/learn/execution-persistence-privilege-escalation-and-evasion', 0, 4.3),
(72, 'Cloud Top Ten Risks', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/e9/52711a3f244ceaae92fff2952bf14c/cloud-adm-logo.png?auto=format%2Ccompress&dpr=2&blur=200&px=8&w=330&h=330', NULL, 'Skills you\'ll gain: Cloud Computing Security, Security Engineering, Software Security, Computer Networking, Cyberattacks, Security', 'https://www.coursera.org/learn/cloud-top-ten-risks', 0, 4.2),
(73, 'Mathematical Foundations for Cryptography', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/76/0cb730aaca11e7b2ec3fdd2fe0097b/cs-4920.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Cryptography, Mathematics, Theoretical Computer Science, Security Engineering, Mathematical Theory & Analysis, Algorithms', 'https://www.coursera.org/learn/mathematical-foundations-cryptography', 0, 4.6);
INSERT INTO `course` (`id`, `name`, `image`, `nb_enrollments`, `details`, `link`, `nb_likes`, `rate`) VALUES
(74, 'Advanced Python - Reconnaissance', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/91/469920f1a348f98ea08af3172e519a/Coursera_Advanced_Python_Scripting_1200x1200.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Software Security, Python Programming, Security Engineering, Computer Programming, System Security, Security Software, Operating Systems, Statistical Programming', 'https://www.coursera.org/learn/python-in-recon', 0, 4.2),
(75, 'Leadership', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/b5/5515a796d24953819ccab57e307766/clm_600x600.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Leadership, Entrepreneurship, Security Engineering, Security Strategy, Strategy and Operations, Leadership and Management, Marketing, Sales, Strategy', 'https://www.coursera.org/learn/cybersecurityleadership', 0, 4.2),
(76, 'Governance and Strategy', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/83/3a80321aef4dea974ba09a19e6c644/Coursera-Cybersecurity-Leadership-and-Management-600x600.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=f', NULL, 'Skills you\'ll gain: Risk Management, Security Engineering, Entrepreneurship, Leadership and Management, Finance, Strategy and Operations, Security Strategy, Sales, Marketing, Strategy', 'https://www.coursera.org/learn/cybersecurity-governance-and-strategy', 0, 4.3),
(77, 'Management', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0a/7584c911bb47be983066b57d16a27c/clm_600x600.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Skills you\'ll gain: Corporate Bond, Leadership and Management', 'https://www.coursera.org/learn/cybersecuritymanagement', 0, 4.9),
(78, 'Check Point Jump Start: Harmony Endpoint Security', 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/17/c79b93c2b245e8bccb1fd0e46499e1/JumpStart_Harmony_800x800.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25', NULL, 'Free', 'https://www.coursera.org/learn/check-point-jump-start-harmony-endpoint-security', 0, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `course`
--
ALTER TABLE `course`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `course`
--
ALTER TABLE `course`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
